#!/usr/bin/env python
import json

import argh
from argh import arg

from biolit.esindex import es_index_pairsfile
from biolit.sandbox.pairs import cpairs, view_withcytoscape

"""
Command line interface for biolit project
This script is added to user PATH when a package installation made
"""

@arg('ontology1', help='File for the first ontology')
@arg('concept1', help='Term id of the root concept in the first ontology')
@arg('ontology2', help='File for the second ontology')
@arg('concept2', help='Term id of the root concept in the second ontology')
@arg('--index', help='Elasticsearch index name; pmc for PMC, pubmed for PubMed')
def findpairs(ontology1, concept1, ontology2, concept2, index='pmc'):
    """
    Find concept pairs and their association scores in the literature,
    for two concepts and their child concepts specified by the params
    ontology1, concept1, ontology2, concept2.
    """
    r = cpairs(ontology1, concept1, ontology2, concept2, index)
    print(json.dumps(r, indent=4))

def index(infile):
    """
    Index concept pairs with Elasticsearch
     """
    r = es_index_pairsfile(infile)
    print("#documents indexed: %d" % r)

@arg('infile', help='Association pairs file, generated with the'
                    ' findpairs command')
def cyview(infile):
    """
    See concept pairs with Cytoscape desktop app
     """
    view_withcytoscape(infile)


if __name__ == '__main__':
    argh.dispatch_commands([
        findpairs, index, cyview
    ])
